name: Setup Composite Action
description: Sets up GitHub Actions runner to build, test, and publish images

runs:
  using: composite
  steps:
    - name: Load Build Arguments
      shell: bash
      run: cat .env >> $GITHUB_ENV

    - name: Set up Docker
      uses: docker/setup-docker-action@v5
      with:
        daemon-config: |
          {
            "features": {
              "containerd-snapshotter": true
            }
          }

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v4

    # Workaround for "qemu: uncaught target signal 11 (Segmentation fault)" error for
    # multi-platform builds with Buildx on GitHub Actions runners
    # https://github.com/docker/buildx/issues/1170
    - name: Workaround for QEMU error
      shell: bash
      run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes -c yes

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v4
