name: Setup Composite Action
description: Sets up GitHub Actions runner to build, test, and publish images

runs:
  using: composite
  steps:
    - name: Load Build Arguments
      shell: bash
      run: cat .env >> $GITHUB_ENV

    - name: Set up Docker
      uses: docker/setup-docker-action@v5
      with:
        daemon-config: |
          {
            "features": {
              "containerd-snapshotter": true
            }
          }
